logFilters:
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.0.0.cjs
